### PR TITLE
NIO-1026, getting absolute path through nio to so that it gets prefix…

### PR DESCRIPTION
**Pull request by f1401martin**
…ed with the project's path

### CODE REVIEW

**Review by mattdodge — CHANGES_REQUESTED** [review]
The problem with this is that it creates a dependency on `niocore` within the module implementation, something we have said we shouldn't do.

What is the use case driving this? We've been able to make most things work in the past using the project root environment variable `[[ PROJECT_ROOT ]]`.

**Comment by f1401martin** [comment]
@mattdodge This PR addresses NIO-1026, https://neutralio.atlassian.net/browse/NIO-1026, certainly we can include [[PROJECT_ROOT]] and recommend to use absolute paths every time but wonder if that is sufficient, I think it is generally understood that a relative path would be relative to project folder, not sure of any other way to enforce this, having said that, there are ways to mitigate the side effect of hoping your current directory is the one desired for your relative path, namely making sure any other part of the software that changes directory makes sure previous current directory is restored or pass the project directory along in the context and components/modules that need it make use of it (this would remove the dependency on niocore's environment solving the issue in a definite manner), please take a look at NIO-1026 and ping me to discuss.

**Comment by mattdodge** [comment]
I don't know if I understand how this PR fixes the error in that JIRA ticket. There seems to have been an error calling `os.getcwd`? How does the working directory get "deleted"? I'd rather do something like have the core set the working directory to the project root when a service is launched. I would have expected that to happen anyway with the `multiprocess` module but maybe it doesn't?

**Comment by f1401martin** [comment]
The working directory, which happened to be a block downloaded from nio-blocks, was deleted manually

**Comment by mattdodge** [comment]
Ohhh I see, so the directory was deleted, interesting. In that case, yeah, I would expect that the project manager would not keep the current working directory as the block directory once it is cloned. Sounds like the bug is there.

**Comment by f1401martin** [comment]
Closing this since fix is tackled at the root problem (project manager component being careless by not restoring current directory)

**Pull request closed without merging**
